language: perl

os:
    - linux
    - osx

env:
    global:
        - secure: "ZNfftSooxOujGRl54eynKERBnIMpOIXHxUwyaJUL4OXEY2BPXFukMswaggFpLzPRh6VK0Kp2kB1/xWsQeS0gcJpfHivY6i3u8J44fH65ddEHdIP/ekv/sHblBAfhdz2OYqe52TS4s1l1M/aTBmHJR6jAZEdkM8yMz0S0bN4yWY0f2bBSO51UgKGGXXpj2NpPO7ySheFZHAunyD2Rl/EqlyryAkNnhQ4+EqtG7UNhSGywQdfMyjiINDpbtfNt96RcWH1bvs2tybfh2x5nJkaNs/mFTyUlWlBRLOX8GcPJE1wbWwNx+cXBK02KPHPKaA6cikdwdxZn43bJOR4eA8cB4/N1gdJ8mDyGg8SdYLFfoYWOGfpDKkakzGMr8AKipHojTbV5l5ac94qjcOnetWIJxzoYojXYeb6V2aA5UOvVr1urqqmbBj6EcPwpvaNnejB3uzSzrAhmNzZCiEQlbMCmAy/MfG/om442BY3ffy1TlsKIUbtG7v5WqIzgALfbhcxEibZdJll6tkA7mfWj/6SVLgLYxf4b9yJIWH+E9Zgort9jWy5qBOJL8Hv4b1urQO8gSUeKVrw+JxzEWQnfKThnWQfq7TsCR89508Hr67vqzjVLSI0luzJDjjL9RD8VS76oaY93oH0a9BoJrct/8YKoq/ltcZ202H+4m2M/SKDjldo="
    matrix:
        - BACKEND=moar
        - BACKEND=jvm

matrix:
    allow_failures:
        - env: BACKEND=jvm
    fast_finish: true

sudo: false

before_install:
    - 'if [[ $BACKEND == "moar" ]]; then export VM_OPTS="--gen-moar"; fi'
    - git clone https://github.com/rakudo/rakudo.git $HOME/rakudo
    - cd $HOME/rakudo
    - perl Configure.pl $VM_OPTS --gen-nqp --backends=$BACKEND
    - make install
    - export PATH=$HOME/rakudo/install/bin:$PATH
    - export PATH=$HOME/rakudo/install/share/perl6/site/bin:$PATH
    - cd $TRAVIS_BUILD_DIR

install:
    - git clone https://github.com/ugexe/zef $HOME/zef
    - perl6 -I $HOME/zef $HOME/zef/bin/zef --deps-only install .

script:
    - prove -v -e 'perl6 -I.' t/
